// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChWrtZshqGrOhmUzQpWWI6BDFZ8-BQiX8',
    appId: '1:622893302643:web:d7cc4c33a5c59a19bc3b06',
    messagingSenderId: '622893302643',
    projectId: 'flutter-practice-app-3628b',
    authDomain: 'flutter-practice-app-3628b.firebaseapp.com',
    storageBucket: 'flutter-practice-app-3628b.firebasestorage.app',
    measurementId: 'G-5Y66C575XP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdqcU5vH6k-tg2rVtL1oTs2ZXKFuAXYnU',
    appId: '1:622893302643:android:40a39e2d6c3863a4bc3b06',
    messagingSenderId: '622893302643',
    projectId: 'flutter-practice-app-3628b',
    storageBucket: 'flutter-practice-app-3628b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDycfAazqjjB1U6G8NWXu2_R_HGyXcecc',
    appId: '1:622893302643:ios:95c515c834265732bc3b06',
    messagingSenderId: '622893302643',
    projectId: 'flutter-practice-app-3628b',
    storageBucket: 'flutter-practice-app-3628b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDycfAazqjjB1U6G8NWXu2_R_HGyXcecc',
    appId: '1:622893302643:ios:95c515c834265732bc3b06',
    messagingSenderId: '622893302643',
    projectId: 'flutter-practice-app-3628b',
    storageBucket: 'flutter-practice-app-3628b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChWrtZshqGrOhmUzQpWWI6BDFZ8-BQiX8',
    appId: '1:622893302643:web:6e2a5211db514d3fbc3b06',
    messagingSenderId: '622893302643',
    projectId: 'flutter-practice-app-3628b',
    authDomain: 'flutter-practice-app-3628b.firebaseapp.com',
    storageBucket: 'flutter-practice-app-3628b.firebasestorage.app',
    measurementId: 'G-8MT9P10PX7',
  );
}
