import Model, { attr, belongsTo, hasMany } from '@ember-data/model';
import BaseModel from './base';

export default class WiFiRadioModel extends BaseModel {
  static sanitizedFields = []; // leave empty to sanitize all strings
  
  @attr AP_Mode;
  @attr ActiveAntennaCtrl;
  @attr ActiveAssociatedDevices;
  @attr ActiveVideoAssociatedDevices;
  @attr AirtimeFairnessEnabled;
  @attr Alias;
  @attr AutoBandwidthSelectMode;
  @attr AutoChannelEnable;
  @attr AutoChannelRefreshPeriod;
  @attr AutoChannelSupported;
  @attr BaseMACAddress;
  @attr BeaconPeriod;
  @attr Channel;
  @attr ChannelBandwidthChangeReason;
  @attr ChannelChangeReason;
  @attr ChannelLoad;
  @attr ChannelsInUse;
  @attr CurrentOperatingChannelBandwidth;
  @attr DFSChannelChangeEventCounter;
  @attr DFSChannelChangeEventTimestamp;
  @attr DTIMInterval;
  @attr DTIMPeriod;
  @attr DelayApUpPeriod;
  @attr Enable;
  @attr ExplicitBeamFormingEnabled;
  @attr ExplicitBeamFormingSupported;
  @attr ExtensionChannel;
  @attr FirmwareVersion;
  // @attr FragmentationThreshold;
  @attr RTSThreshold;
  @attr GuardInterval;
  @attr HECapabilities;
  @attr HTCapabilities;
  @attr HeCapsEnabled;
  @attr HeCapsSupported;
  @attr IEEE80211_Caps;
  @attr IEEE80211hEnabled;
  @attr IEEE80211hSupported;
  @attr IEEE80211kSupported;
  @attr IEEE80211rSupported;
  @attr ImplicitBeamFormingEnabled;
  @attr ImplicitBeamFormingSupported;
  @attr Index;
  @attr IntelligentAirtimeSchedulingEnable;
  @attr Interference;
  @attr KickRoamingStation;
  @attr LastStatusChangeTimeStamp;
  @attr LongRetryLimit;
  @attr LowerLayers;
  @attr MCS;
  @attr MaxAssociatedDevices;
  @attr MaxBitRate;
  @attr MaxChannelBandwidth;
  @attr MaxSupportedSSIDs;
  @attr MultiAPTypesSupported;
  @attr MultiUserMIMOEnabled;
  @attr MultiUserMIMOSupported;
  @attr Name;
  @attr Noise;
  @attr ObssCoexistenceEnable;
  @attr OfdmaEnable;
  @attr OperatingChannelBandwidth;
  @attr OperatingClass;
  @attr OperatingFrequencyBand;
  @attr OperatingStandards;
  @attr OperatingStandardsFormat;
  @attr PossibleChannels;
  @attr RIFSEnabled;
  @attr RadCapabilitiesHTStr;
  @attr RadCapabilitiesHePhysStr;
  @attr RadCapabilitiesVHTStr;
  @attr RegulatoryDomain;
  @attr RetryLimit;
  @attr RxBeamformingCapsAvailable;
  @attr RxBeamformingCapsEnabled;
  @attr RxChainCtrl;
  @attr RxPowerSaveEnabled;
  @attr RxPowerSaveRepeaterEnable;
  @attr STASupported_Mode;
  @attr STA_Mode;
  @attr Status;
  @attr SupportedFrequencyBands;
  @attr SupportedOperatingChannelBandwidth;
  @attr SupportedStandards;
  @attr TargetWakeTimeEnable;
  @attr TransmitPower;
  @attr TransmitPowerSupported;
  @attr TxBeamformingCapsAvailable;
  @attr TxBeamformingCapsEnabled;
  @attr TxChainCtrl;
  @attr Upstream;
  @attr VHTCapabilities;
  @attr VendorPCISig;
  @attr WDS_Mode;
  @attr WET_Mode;
  @attr WPS_Enrollee_Mode;
  @attr dbgRADEnable;
  @attr dbgRADFile;
  @belongsTo('wifi-radio-driverconfig') DriverConfig;

  @attr({
    defaultValue() { return 'WiFi.Radio.'; }
  }) _namespace;
}
